### ISSUE TITLE
Http/2

### ISSUE THREAD

**Issue by nguyenhothanhtam0709** [naviserver-project/naviserver#2]
I'm thinking about using naviserver to build a tcl web app. But I'm not sure about http/2 support in naviserver. Does naviserver support http/2?

**Comment by gustafn** [comment]
The public release of NaviServer does not support HTTP/2. We have an experimental implementation presented at the EuroTcl/OpenACS conference [1,2], which looks very promising (substantially faster for the "small files" benchmark than Apache and Nginx). For full support, there is still some work needed. Currently, there is more emphasis on our side on Tcl9, and HTTP/3 is probably the better choice for the longer run. Better protocol support will be added, but no promises for a delivery date. For now, probably the best option for h2 is to use NaviServer behind nginx.

[1] https://openacs.org/conf2022/info/schedule
[2] https://openacs.org/conf2022/info/download/file/slides/openacs-conf-2022-naviserver.pdf

**Comment by nguyenhothanhtam0709** [comment]
@gustafn , thanks for your response.

**Comment by gustafn** [comment]
You are welcome!
