### ISSUE TITLE
nscgi does not use  contentfile for  input content 

### ISSUE THREAD

**Issue by ooa64** [naviserver-project/naviserver#5]
Looks like nscgi module does not take into account that the incoming content may be in a spool file.
Attempting to make a large (more then maxupload) CGI POST returns status 500.

Log details:
---
Error: nscgi: temp file write failed: Bad address
Warning: internal error (HTTP status 500) (nscgi: cannot spool data, return code -1)
---
Problem exists in the main and 4.99 branches.
Proposed patches to the main branch to reproduce and, possible, fix this problem are attached.
[nscgi.zip](https://github.com/user-attachments/files/18052944/nscgi.zip)

**Comment by gustafn** [comment]
Many thanks for fix. It is applied on the main branch, and will be cherry-picked to the 4.99 branch after the release of 5.0
